// Build a public-domain US state + county SVG map.
// Data: US Census Bureau cartographic boundary files via the us-atlas package
// (pre-projected Albers USA composite, 975x610). Census data is public domain;
// us-atlas, d3-geo and topojson-client are ISC-licensed.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoPath } from "d3-geo";
import { feature, mesh } from "topojson-client";
const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("us-atlas/counties-albers-10m.json"), "utf8"));
const FIPS = {"01":"AL","02":"AK","04":"AZ","05":"AR","06":"CA","08":"CO","09":"CT","10":"DE","11":"DC","12":"FL","13":"GA","15":"HI","16":"ID","17":"IL","18":"IN","19":"IA","20":"KS","21":"KY","22":"LA","23":"ME","24":"MD","25":"MA","26":"MI","27":"MN","28":"MS","29":"MO","30":"MT","31":"NE","32":"NV","33":"NH","34":"NJ","35":"NM","36":"NY","37":"NC","38":"ND","39":"OH","40":"OK","41":"OR","42":"PA","44":"RI","45":"SC","46":"SD","47":"TN","48":"TX","49":"UT","50":"VT","51":"VA","53":"WA","54":"WV","55":"WI","56":"WY"};
const path = geoPath(); // already projected
const states = feature(topo, topo.objects.states).features.filter(f => FIPS[f.id]);
const counties = feature(topo, topo.objects.counties).features.filter(f => FIPS[f.id.slice(0,2)]);
const esc = s => s.replace(/&/g,"&amp;").replace(/"/g,"&quot;");
let out = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 975 610" role="img" aria-labelledby="map-title" class="us-map">
<title id="map-title">United States map: corporal punishment in public schools, by state and county</title>
<!-- Boundaries: US Census Bureau cartographic boundary files (public domain), via us-atlas (ISC). Generated by tools/map/build-map.mjs -->
<g id="counties">
`;
for (const c of counties) {
  const st = FIPS[c.id.slice(0,2)];
  out += `<path class="county" data-fips="${c.id}" data-state="${st}" data-name="${esc(c.properties.name)}" d="${path(c)}"/>\n`;
}
out += `</g>\n<g id="states">\n`;
for (const s of states) {
  out += `<path class="state" id="state-${FIPS[s.id]}" data-fips="${s.id}" data-state="${FIPS[s.id]}" data-name="${esc(s.properties.name)}" d="${path(s)}"><title>${esc(s.properties.name)}</title></path>\n`;
}
out += `</g>\n<path id="state-borders" fill="none" stroke="currentColor" stroke-linejoin="round" d="${path(mesh(topo, topo.objects.states, (a,b) => a !== b))}"/>\n</svg>\n`;
writeFileSync(process.argv[2] || "us-map.svg", out);
// State-only lightweight map for the OG image / embeds
let small = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 975 610" class="us-map us-map-states">\n<!-- US Census Bureau boundaries (public domain) via us-atlas (ISC). -->\n`;
for (const s of states) small += `<path class="state" id="state-${FIPS[s.id]}" data-state="${FIPS[s.id]}" data-name="${esc(s.properties.name)}" d="${path(s)}"><title>${esc(s.properties.name)}</title></path>\n`;
small += `</svg>\n`;
writeFileSync(process.argv[3] || "us-states.svg", small);
const centroids = Object.fromEntries(states.map(s => [FIPS[s.id], path.centroid(s).map(v => +v.toFixed(1))]));
writeFileSync(process.argv[4] || "state-centroids.json", JSON.stringify(centroids, null, 1));
console.log(`states=${states.length} counties=${counties.length}`);
